# coding: utf-8
#
# user-graph need to be generated by the following script
# tools/generate-u-u-matrix.py
import os
import numpy as np
import scipy.sparse as sp
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.checkpoint import checkpoint  # [MEM-INFONCE] chunked contrastive denominator
from torch_geometric.nn.conv import MessagePassing
from torch_geometric.utils import remove_self_loops, add_self_loops, degree
import torch_geometric

from common.abstract_recommender import GeneralRecommender
from common.loss import BPRLoss, EmbLoss
from common.init import xavier_uniform_initialization


class ResidualFeatureAdapter(nn.Module):
    def __init__(self, input_dim, bottleneck_dim, dropout, alpha):
        super().__init__()
        self.norm = nn.LayerNorm(input_dim, elementwise_affine=False)
        self.down = nn.Linear(input_dim, bottleneck_dim)
        self.up = nn.Linear(bottleneck_dim, input_dim)
        self.dropout = nn.Dropout(dropout)
        self.alpha = alpha
        nn.init.zeros_(self.up.weight)
        nn.init.zeros_(self.up.bias)

    def forward(self, features):
        residual = self.up(self.dropout(F.gelu(self.down(self.norm(features)))))
        return features + self.alpha * residual


class MENTOR(GeneralRecommender):
    def __init__(self, config, dataset):
        super(MENTOR, self).__init__(config, dataset)

        num_user = self.n_users
        num_item = self.n_items
        batch_size = config['train_batch_size']  # not used
        dim_x = config['embedding_size']
        self.feat_embed_dim = config['feat_embed_dim']
        self.n_layers = config['n_mm_layers']
        self.knn_k = config['knn_k']
        self.mm_image_weight = config['mm_image_weight']

        self.batch_size = batch_size
        self.num_user = num_user
        self.num_item = num_item
        self.k = 40
        self.aggr_mode = 'add'
        self.dataset = dataset
        self.dropout = config['dropout']
        # self.construction = 'weighted_max'
        self.reg_weight = config['reg_weight']
        self.align_weight = config['align_weight']
        self.mask_weight_g = config['mask_weight_g']
        self.mask_weight_f = config['mask_weight_f']
        self.temp = config['temp']
        self.use_id_residual = bool(config['use_id_residual'])
        self.use_feature_adapter = bool(config['use_feature_adapter'])
        # ===== [GRAPH-REFRESH] rebuild mm_adj from adapted features every N epochs (0 = off) =====
        self.mm_adj_refresh_interval = int(config['mm_adj_refresh_interval'] or 0)
        self._pre_epoch_calls = 0
        # ===== [GRAPH-REFRESH] end =====
        # ===== [SSM] ranking loss: 'bpr' (original) or 'softmax' over K sampled negatives =====
        self.loss_type = (config['loss_type'] or 'bpr').lower()
        self.ssm_temp = float(config['ssm_temp'] or 1.0)
        self.hard_bpr_weight = float(config['hard_bpr_weight'] or 0.0)
        # [DNS] dynamic hard-negative selection: dataloader draws num_negatives as a POOL,
        # the loss keeps only the dns_keep highest-scoring ones (0 = off, use all).
        # dns_veto additionally excludes the positive's content-kNN lookalikes from
        # selection (mm_adj as a false-negative filter rather than a negative source).
        self.dns_keep = int(config['dns_keep'] or 0)
        self.dns_random_keep = int(config['dns_random_keep'] or 0)
        self.dns_strategy = (config['dns_strategy'] or 'hard').lower()
        if self.dns_strategy not in ('hard', 'semi_hard', 'mixed_semi_hard'):
            raise ValueError('Unsupported dns_strategy: {}'.format(self.dns_strategy))
        self.dns_veto = bool(config['dns_veto'])
        self._lookalike_ids = None
        # ===== [SSM] end =====
        self.drop_rate = 0.1
        self.v_rep = None
        self.t_rep = None
        self.v_preference = None
        self.t_preference = None
        self.id_preference = None
        self.dim_latent = 64
        self.dim_feat = 128
        self.mm_adj = None

        self.mlp = nn.Linear(2*dim_x, 2*dim_x)

        dataset_path = os.path.abspath(config['data_path'] + config['dataset'])
        # [OPTIONAL-UGRAPH] user_graph_dict feeds only topk_sample, whose outputs are never
        # used in forward()/calculate_loss() (dead DualGNN leftover). Make it optional so
        # datasets without the precomputed file (sports/clothing) can still run.
        user_graph_path = os.path.join(dataset_path, config['user_graph_dict_file'])
        if os.path.exists(user_graph_path):
            self.user_graph_dict = np.load(user_graph_path, allow_pickle=True).item()
        else:
            self.user_graph_dict = None

        mm_adj_file = os.path.join(dataset_path, 'mm_adj_{}.pt'.format(self.knn_k))

        if self.v_feat is not None:
            self.image_embedding = nn.Embedding.from_pretrained(self.v_feat, freeze=False)
            self.image_trs = nn.Linear(self.v_feat.shape[1], self.feat_embed_dim)
        if self.t_feat is not None:
            self.text_embedding = nn.Embedding.from_pretrained(self.t_feat, freeze=False)
            self.text_trs = nn.Linear(self.t_feat.shape[1], self.feat_embed_dim)

        if self.use_feature_adapter and self.v_feat is not None:
            self.visual_adapter = ResidualFeatureAdapter(
                self.v_feat.shape[1],
                config['feature_adapter_dim'] or 64,
                config['feature_adapter_dropout'] or 0.1,
                config['feature_adapter_alpha'] or 0.1,
            )
        else:
            self.visual_adapter = None

        if self.use_feature_adapter and self.t_feat is not None:
            self.text_adapter = ResidualFeatureAdapter(
                self.t_feat.shape[1],
                config['feature_adapter_dim'] or 64,
                config['feature_adapter_dropout'] or 0.1,
                config['feature_adapter_alpha'] or 0.1,
            )
        else:
            self.text_adapter = None

        if os.path.exists(mm_adj_file):
            self.mm_adj = torch.load(mm_adj_file)
        else:
            if self.v_feat is not None:
                indices, image_adj = self.get_knn_adj_mat(self.image_embedding.weight.detach())
                self.mm_adj = image_adj
            if self.t_feat is not None:
                indices, text_adj = self.get_knn_adj_mat(self.text_embedding.weight.detach())
                self.mm_adj = text_adj
            if self.v_feat is not None and self.t_feat is not None:
                self.mm_adj = self.mm_image_weight * image_adj + (1.0 - self.mm_image_weight) * text_adj
                del text_adj
                del image_adj
            torch.save(self.mm_adj, mm_adj_file)

        # packing interaction in training into edge_index
        train_interactions = dataset.inter_matrix(form='coo').astype(np.float32)
        edge_index = self.pack_edge_index(train_interactions)
        self.edge_index = torch.tensor(edge_index, dtype=torch.long).t().contiguous().to(self.device)
        self.edge_index = torch.cat((self.edge_index, self.edge_index[[1, 0]]), dim=1)
        # pdb.set_trace()
        self.weight_u = nn.Parameter(nn.init.xavier_normal_(
            torch.tensor(np.random.randn(self.num_user, 2, 1), dtype=torch.float32, requires_grad=True)))
        self.weight_u.data = F.softmax(self.weight_u, dim=1)

        self.weight_i = nn.Parameter(nn.init.xavier_normal_(
            torch.tensor(np.random.randn(self.num_item, 2, 1), dtype=torch.float32, requires_grad=True)))
        self.weight_i.data = F.softmax(self.weight_i, dim=1)

        self.item_index = torch.zeros([self.num_item], dtype=torch.long)
        index = []
        for i in range(self.num_item):
            self.item_index[i] = i
            index.append(i)
        self.drop_percent = self.drop_rate
        self.single_percent = 1
        self.double_percent = 0

        drop_item = torch.tensor(
            np.random.choice(self.item_index, int(self.num_item * self.drop_percent), replace=False))
        drop_item_single = drop_item[:int(self.single_percent * len(drop_item))]

        self.dropv_node_idx_single = drop_item_single[:int(len(drop_item_single) * 1 / 3)]
        self.dropt_node_idx_single = drop_item_single[int(len(drop_item_single) * 2 / 3):]

        self.dropv_node_idx = self.dropv_node_idx_single
        self.dropt_node_idx = self.dropt_node_idx_single

        mask_cnt = torch.zeros(self.num_item, dtype=int).tolist()
        for edge in edge_index:
            mask_cnt[edge[1] - self.num_user] += 1
        mask_dropv = []
        mask_dropt = []
        for idx, num in enumerate(mask_cnt):
            temp_false = [False] * num
            temp_true = [True] * num
            mask_dropv.extend(temp_false) if idx in self.dropv_node_idx else mask_dropv.extend(temp_true)
            mask_dropt.extend(temp_false) if idx in self.dropt_node_idx else mask_dropt.extend(temp_true)

        edge_index = edge_index[np.lexsort(edge_index.T[1, None])]
        edge_index_dropv = edge_index[mask_dropv]
        edge_index_dropt = edge_index[mask_dropt]

        self.edge_index_dropv = torch.tensor(edge_index_dropv).t().contiguous().to(self.device)
        self.edge_index_dropt = torch.tensor(edge_index_dropt).t().contiguous().to(self.device)

        self.edge_index_dropv = torch.cat((self.edge_index_dropv, self.edge_index_dropv[[1, 0]]), dim=1)
        self.edge_index_dropt = torch.cat((self.edge_index_dropt, self.edge_index_dropt[[1, 0]]), dim=1)

        self.MLP_user = nn.Linear(self.dim_latent * 2, self.dim_latent)
        self.id_residual_weight = nn.Parameter(torch.zeros(1))

        if self.v_feat is not None:
            self.v_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode, dim_latent=64,
                             device=self.device, features=self.v_feat)
            self.v_gcn_n1 = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode, dim_latent=64,
                             device=self.device, features=self.v_feat)
            self.v_gcn_n2 = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode, dim_latent=64,
                                device=self.device, features=self.v_feat)
        if self.t_feat is not None:
            self.t_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode, dim_latent=64,
                             device=self.device, features=self.t_feat)
            self.t_gcn_n1 = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode, dim_latent=64,
                             device=self.device, features=self.t_feat)
            self.t_gcn_n2 = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode, dim_latent=64,
                                device=self.device, features=self.t_feat)

        self.id_feat = nn.Parameter(
            nn.init.xavier_normal_(torch.tensor(np.random.randn(self.n_items, self.dim_latent), dtype=torch.float32,
                                                requires_grad=True), gain=1).to(self.device))
        self.id_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
                          dim_latent=64, device=self.device, features=self.id_feat)


        self.result_embed = None
        self.result_embed_guide = None
        self.result_embed_v = None
        self.result_embed_t = None
        self.result_embed_n1 = None
        self.result_embed_n2 = None

    def get_knn_adj_mat(self, mm_embeddings):
        context_norm = mm_embeddings.div(torch.norm(mm_embeddings, p=2, dim=-1, keepdim=True))
        sim = torch.mm(context_norm, context_norm.transpose(1, 0))
        _, knn_ind = torch.topk(sim, self.knn_k, dim=-1)
        adj_size = sim.size()
        del sim
        # construct sparse adj
        indices0 = torch.arange(knn_ind.shape[0]).to(self.device)
        indices0 = torch.unsqueeze(indices0, 1)
        indices0 = indices0.expand(-1, self.knn_k)
        indices = torch.stack((torch.flatten(indices0), torch.flatten(knn_ind)), 0)
        # norm
        return indices, self.compute_normalized_laplacian(indices, adj_size)

    def compute_normalized_laplacian(self, indices, adj_size):
        adj = torch.sparse.FloatTensor(indices, torch.ones_like(indices[0]), adj_size)
        row_sum = 1e-7 + torch.sparse.sum(adj, -1).to_dense()
        r_inv_sqrt = torch.pow(row_sum, -0.5)
        rows_inv_sqrt = r_inv_sqrt[indices[0]]
        cols_inv_sqrt = r_inv_sqrt[indices[1]]
        values = rows_inv_sqrt * cols_inv_sqrt
        return torch.sparse.FloatTensor(indices, values, adj_size)

    def pre_epoch_processing(self):
        # [OPTIONAL-UGRAPH] skip the (unused) user-graph resampling when the dict is absent
        if self.user_graph_dict is not None:
            self.epoch_user_graph, self.user_weight_matrix = self.topk_sample(self.k)
            self.user_weight_matrix = self.user_weight_matrix.to(self.device)
        # ===== [GRAPH-REFRESH] periodically rebuild the item kNN graph from adapted features =====
        self._pre_epoch_calls += 1
        if (self.mm_adj_refresh_interval > 0 and self.use_feature_adapter
                and self._pre_epoch_calls % self.mm_adj_refresh_interval == 0):
            self._refresh_mm_adj()
        # ===== [GRAPH-REFRESH] end =====

    # ===== [GRAPH-REFRESH] in-memory rebuild; never overwrites the cached mm_adj file =====
    def _refresh_mm_adj(self):
        import time
        start = time.time()
        with torch.no_grad():
            image_adj, text_adj = None, None
            if self.v_feat is not None:
                _, image_adj = self.get_knn_adj_mat(self.adapted_visual_features())
            if self.t_feat is not None:
                _, text_adj = self.get_knn_adj_mat(self.adapted_text_features())
            if image_adj is not None and text_adj is not None:
                self.mm_adj = self.mm_image_weight * image_adj + (1.0 - self.mm_image_weight) * text_adj
            elif image_adj is not None:
                self.mm_adj = image_adj
            else:
                self.mm_adj = text_adj
        print('[GRAPH-REFRESH] rebuilt mm_adj from adapted features at epoch call {} ({:.1f}s)'.format(
            self._pre_epoch_calls, time.time() - start), flush=True)
    # ===== [GRAPH-REFRESH] end =====

    def pack_edge_index(self, inter_mat):
        rows = inter_mat.row
        cols = inter_mat.col + self.n_users
        # ndarray([598918, 2]) for ml-imdb
        return np.column_stack((rows, cols))

    def InfoNCE(self, view1, view2, temp):
        view1, view2 = F.normalize(view1, dim=1), F.normalize(view2, dim=1)
        pos_score = (view1 * view2).sum(dim=-1)
        pos_score = torch.exp(pos_score / temp)
        # [MEM-INFONCE] The denominator is a full N×N similarity matrix; materialising it
        # OOMs on larger datasets (sports/clothing on a 15GB GPU). Compute it in row-blocks
        # with gradient checkpointing so the [chunk, N] block is recomputed in backward
        # instead of stored — identical math, peak memory drops from N×N to chunk×N.
        ttl_score = self._infonce_denominator(view1, view2, temp)
        cl_loss = -torch.log(pos_score / ttl_score)
        return torch.mean(cl_loss)

    def _infonce_denominator(self, view1, view2, temp, chunk=4096):
        def block_sum(v1_chunk):
            sim = torch.matmul(v1_chunk, view2.transpose(0, 1))
            return torch.exp(sim / temp).sum(dim=1)
        n = view1.shape[0]
        outs = []
        for i in range(0, n, chunk):
            v1_chunk = view1[i:i + chunk]
            if self.training and v1_chunk.requires_grad:
                outs.append(checkpoint(block_sum, v1_chunk, use_reentrant=False))
            else:
                outs.append(block_sum(v1_chunk))
        return torch.cat(outs, dim=0)

    def adapted_visual_features(self):
        if self.visual_adapter is None:
            return self.v_feat
        return self.visual_adapter(self.v_feat)

    def adapted_text_features(self):
        if self.text_adapter is None:
            return self.t_feat
        return self.text_adapter(self.t_feat)

    def forward(self, interaction):
        user_nodes = interaction[0]
        pos_item_nodes = interaction[1] + self.n_users
        neg_item_nodes = interaction[2] + self.n_users
        v_feat = self.adapted_visual_features()
        t_feat = self.adapted_text_features()

        # GCN for id, v, t modalities
        self.v_rep, self.v_preference = self.v_gcn(self.edge_index_dropv, self.edge_index, v_feat)
        self.t_rep, self.t_preference = self.t_gcn(self.edge_index_dropt, self.edge_index, t_feat)
        self.id_rep, self.id_preference = self.id_gcn(self.edge_index_dropt, self.edge_index, self.id_feat)

        # random noise GCN for v and t
        self.v_rep_n1, _ = self.v_gcn_n1(self.edge_index_dropv, self.edge_index, v_feat, perturbed=True)
        self.t_rep_n1, _ = self.t_gcn_n1(self.edge_index_dropt, self.edge_index, t_feat, perturbed=True)
        self.v_rep_n2, _ = self.v_gcn_n2(self.edge_index_dropv, self.edge_index, v_feat, perturbed=True)
        self.t_rep_n2, _ = self.t_gcn_n2(self.edge_index_dropt, self.edge_index, t_feat, perturbed=True)

        # v, v, id, and vt modalities
        representation = torch.cat((self.v_rep, self.t_rep), dim=1)
        guide_representation = torch.cat((self.id_rep, self.id_rep), dim=1)
        v_representation = torch.cat((self.v_rep, self.v_rep), dim=1)
        t_representation = torch.cat((self.t_rep, self.t_rep), dim=1)

        # noise rep
        representation_n1 = torch.cat((self.v_rep_n1, self.t_rep_n1), dim=1)
        representation_n2 = torch.cat((self.v_rep_n2, self.t_rep_n2), dim=1)

        self.v_rep = torch.unsqueeze(self.v_rep, 2)
        self.t_rep = torch.unsqueeze(self.t_rep, 2)
        self.id_rep = torch.unsqueeze(self.id_rep, 2)

        user_rep = torch.cat((self.v_rep[:self.num_user], self.t_rep[:self.num_user]), dim=2)
        user_rep = self.weight_u.transpose(1, 2) * user_rep
        user_rep = torch.cat((user_rep[:, :, 0], user_rep[:, :, 1]), dim=1)


        guide_user_rep = torch.cat((self.id_rep[:self.num_user], self.id_rep[:self.num_user]), dim=2)
        # guide_user_rep = self.weight_u.transpose(1, 2) * guide_user_rep
        guide_user_rep = torch.cat((guide_user_rep[:, :, 0], guide_user_rep[:, :, 1]), dim=1)

        v_user_rep = torch.cat((self.v_rep[:self.num_user], self.v_rep[:self.num_user]), dim=2)
        # v_user_rep = self.weight_u.transpose(1, 2) * v_user_rep
        v_user_rep = torch.cat((v_user_rep[:, :, 0], v_user_rep[:, :, 1]), dim=1)

        t_user_rep = torch.cat((self.t_rep[:self.num_user], self.t_rep[:self.num_user]), dim=2)
        # t_user_rep = self.weight_u.transpose(1, 2) * t_user_rep
        t_user_rep = torch.cat((t_user_rep[:, :, 0], t_user_rep[:, :, 1]), dim=1)

        # noise rep1
        self.v_rep_n1 = torch.unsqueeze(self.v_rep_n1, 2)
        self.t_rep_n1 = torch.unsqueeze(self.t_rep_n1, 2)
        user_rep_n1 = torch.cat((self.v_rep_n1[:self.num_user], self.t_rep_n1[:self.num_user]), dim=2)
        user_rep_n1 = self.weight_u.transpose(1, 2) * user_rep_n1
        user_rep_n1 = torch.cat((user_rep_n1[:, :, 0], user_rep_n1[:, :, 1]), dim=1)

        # noise rep2
        self.v_rep_n2 = torch.unsqueeze(self.v_rep_n2, 2)
        self.t_rep_n2 = torch.unsqueeze(self.t_rep_n2, 2)
        user_rep_n2 = torch.cat((self.v_rep_n2[:self.num_user], self.t_rep_n2[:self.num_user]), dim=2)
        user_rep_n2 = self.weight_u.transpose(1, 2) * user_rep_n2
        user_rep_n2 = torch.cat((user_rep_n2[:, :, 0], user_rep_n2[:, :, 1]), dim=1)

        item_rep = representation[self.num_user:]
        item_rep_n1 = representation_n1[self.num_user:]
        item_rep_n2 = representation_n2[self.num_user:]

        guide_item_rep = guide_representation[self.num_user:]
        v_item_rep = v_representation[self.num_user:]
        t_item_rep = t_representation[self.num_user:]

        # build item-item graph
        h = self.buildItemGraph(item_rep)
        h_guide = self.buildItemGraph(guide_item_rep)
        h_v = self.buildItemGraph(v_item_rep)
        h_t = self.buildItemGraph(t_item_rep)
        h_n1 = self.buildItemGraph(item_rep_n1)
        h_n2 = self.buildItemGraph(item_rep_n2)

        user_rep = user_rep
        item_rep = item_rep + h

        item_rep_n1 = item_rep_n1 + h_n1
        item_rep_n2 = item_rep_n2 + h_n2

        guide_item_rep = guide_item_rep + h_guide
        v_item_rep = v_item_rep + h_v
        t_item_rep = t_item_rep + h_t

        # build result embedding
        self.user_rep = user_rep
        self.item_rep = item_rep
        self.result_embed = torch.cat((user_rep, item_rep), dim=0)

        self.guide_user_rep = guide_user_rep
        self.guide_item_rep = guide_item_rep
        self.result_embed_guide = torch.cat((guide_user_rep, guide_item_rep), dim=0)

        self.v_user_rep = v_user_rep
        self.v_item_rep = v_item_rep
        self.result_embed_v = torch.cat((v_user_rep, v_item_rep), dim=0)

        self.t_user_rep = t_user_rep
        self.t_item_rep = t_item_rep
        self.result_embed_t = torch.cat((t_user_rep, t_item_rep), dim=0)

        self.user_rep_n1 = user_rep_n1
        self.item_rep_n1 = item_rep_n1
        self.result_embed_n1 = torch.cat((user_rep_n1, item_rep_n1), dim=0)

        self.user_rep_n2 = user_rep_n2
        self.item_rep_n2 = item_rep_n2
        self.result_embed_n2 = torch.cat((user_rep_n2, item_rep_n2), dim=0)

        # calculate pos and neg scores
        pos_scores = self.score_user_item_pairs(user_nodes, pos_item_nodes - self.n_users)
        neg_scores = self.score_user_item_pairs(user_nodes, neg_item_nodes - self.n_users)
        return pos_scores, neg_scores

    def buildItemGraph(self, h):
        for i in range(self.n_layers):
            h = torch.sparse.mm(self.mm_adj, h)
        return h

    def id_residual_scale(self):
        if not self.use_id_residual:
            return 0.0
        return 0.1 * torch.tanh(self.id_residual_weight)

    def score_user_item_pairs(self, user_ids, item_ids):
        user_tensor = self.result_embed[user_ids]
        item_tensor = self.result_embed[self.n_users + item_ids]
        scores = torch.sum(user_tensor * item_tensor, dim=-1)

        guide_user_tensor = self.result_embed_guide[user_ids]
        guide_item_tensor = self.result_embed_guide[self.n_users + item_ids]
        guide_scores = torch.sum(guide_user_tensor * guide_item_tensor, dim=-1)
        return scores + self.id_residual_scale() * guide_scores

    # ===== [SSM] vectorised scoring for K negatives at once; mirrors score_user_item_pairs =====
    def score_user_items_multi(self, user_ids, item_ids_matrix):
        """user_ids: [B], item_ids_matrix: [K, B] -> scores [K, B]"""
        user_tensor = self.result_embed[user_ids]                              # [B, D]
        item_tensor = self.result_embed[self.n_users + item_ids_matrix]        # [K, B, D]
        scores = (user_tensor.unsqueeze(0) * item_tensor).sum(dim=-1)          # [K, B]

        guide_user = self.result_embed_guide[user_ids]                         # [B, D]
        guide_item = self.result_embed_guide[self.n_users + item_ids_matrix]   # [K, B, D]
        guide_scores = (guide_user.unsqueeze(0) * guide_item).sum(dim=-1)      # [K, B]
        return scores + self.id_residual_scale() * guide_scores

    # ===== [DNS] padded per-item lookalike table from mm_adj (for the veto filter) =====
    def _build_lookalike_table(self):
        adj = self.mm_adj.coalesce()
        rows, cols = adj.indices()
        keep = rows != cols                       # drop self-loops
        rows, cols = rows[keep], cols[keep]
        counts = torch.bincount(rows, minlength=self.num_item)
        max_nb = int(counts.max().item()) if counts.numel() else 1
        table = torch.full((self.num_item, max_nb), -1, dtype=torch.long, device=self.device)
        order = torch.argsort(rows, stable=True)
        r_sorted, c_sorted = rows[order], cols[order]
        group_start = torch.cumsum(counts, 0) - counts
        idx_in_group = torch.arange(len(r_sorted), device=self.device) - torch.repeat_interleave(group_start, counts)
        table[r_sorted, idx_in_group] = c_sorted
        return table                              # -1 padding never matches a real item id
    # ===== [DNS] end =====
    # ===== [SSM] end =====

    def fit_Gaussian_dis(self):
        r_var = torch.var(self.result_embed)
        r_mean = torch.mean(self.result_embed)
        g_var = torch.var(self.result_embed_guide)
        g_mean = torch.mean(self.result_embed_guide)
        v_var = torch.var(self.result_embed_v)
        v_mean = torch.mean(self.result_embed_v)
        t_var = torch.var(self.result_embed_t)
        t_mean = torch.mean(self.result_embed_t)
        return r_var, r_mean, g_var, g_mean, v_var, v_mean, t_var, t_mean

    def calculate_loss(self, interaction):
        user = interaction[0]
        pos_scores, neg_scores = self.forward(interaction)
        # ===== [SSM] sampled softmax over all K negatives; falls back to BPR otherwise =====
        # interaction rows: [user, pos, neg_1, ..., neg_K]; rows 2: are the K negative item ids.
        # (neighbourhood loss is off for MENTOR, so no extra trailing rows to worry about.)
        if self.loss_type == 'softmax':
            neg_ids_matrix = interaction[2:]                                            # [P, B] item ids
            all_neg_scores = self.score_user_items_multi(user, neg_ids_matrix)          # [P, B]
            # ---- [DNS] select a harder subset from the sampled negative pool ----
            if 0 < self.dns_keep < neg_ids_matrix.shape[0]:
                sel_scores = all_neg_scores
                if self.dns_veto:
                    # exclude the positive's content lookalikes: likely substitutes,
                    # i.e. unobserved positives — never train against them as "hard"
                    if self._lookalike_ids is None:
                        self._lookalike_ids = self._build_lookalike_table()
                    nb = self._lookalike_ids[interaction[1]]                            # [B, M]
                    veto = (neg_ids_matrix.unsqueeze(-1) == nb.unsqueeze(0)).any(-1)    # [P, B]
                    sel_scores = all_neg_scores.masked_fill(veto, float('-inf'))
                if self.dns_strategy in ('semi_hard', 'mixed_semi_hard'):
                    # Keep negatives that are confusing but still below the positive score.
                    # If a user has fewer than dns_keep semi-hard candidates, fill the
                    # remaining slots with ordinary hardest negatives so the batch keeps
                    # the requested number of negatives.
                    semi_mask = sel_scores < pos_scores.unsqueeze(0)                    # [P, B]
                    semi_scores = sel_scores.masked_fill(~semi_mask, float('-inf'))
                    top_idx = semi_scores.topk(self.dns_keep, dim=0).indices            # [K, B]
                    picked_scores = semi_scores.gather(0, top_idx)
                    fallback_idx = sel_scores.topk(self.dns_keep, dim=0).indices
                    fallback_scores = sel_scores.gather(0, fallback_idx)
                    picked_idx = torch.where(torch.isfinite(picked_scores),
                                             top_idx, fallback_idx)
                    picked_scores = torch.where(torch.isfinite(picked_scores),
                                                picked_scores, fallback_scores)
                    if self.dns_strategy == 'mixed_semi_hard' and self.dns_random_keep > 0:
                        row_ids = torch.arange(sel_scores.shape[0], device=self.device).view(-1, 1)
                        row_ids = row_ids.expand(-1, sel_scores.shape[1])               # [P, B]
                        already_picked = (row_ids.unsqueeze(0) == picked_idx.unsqueeze(1)).any(0)
                        available = (~already_picked) & torch.isfinite(sel_scores)
                        # Rows are independent random samples from the dataloader, so the
                        # first available rows are random negatives, not score-mined ones.
                        random_rank = -row_ids.float().masked_fill(~available, float('inf'))
                        random_keep = min(self.dns_random_keep, sel_scores.shape[0] - self.dns_keep)
                        random_idx = random_rank.topk(random_keep, dim=0).indices       # [R, B]
                        random_scores = sel_scores.gather(0, random_idx)
                        all_neg_scores = torch.cat((picked_scores, random_scores), dim=0)
                    else:
                        all_neg_scores = picked_scores
                else:
                    top_idx = sel_scores.topk(self.dns_keep, dim=0).indices             # [K, B]
                    all_neg_scores = sel_scores.gather(0, top_idx)                      # -inf-safe
            # ---- [DNS] end ----
            logits = torch.cat((pos_scores.unsqueeze(0), all_neg_scores), dim=0)        # [K+1, B]
            loss_value = -torch.mean(F.log_softmax(logits / self.ssm_temp, dim=0)[0])
            if self.hard_bpr_weight > 0:
                hardest_neg_scores = all_neg_scores.max(dim=0).values
                hard_bpr_loss = -torch.mean(F.logsigmoid(pos_scores - hardest_neg_scores))
                loss_value = loss_value + self.hard_bpr_weight * hard_bpr_loss
        else:
            loss_value = -torch.mean(torch.log2(torch.sigmoid(pos_scores - neg_scores)))
        # ===== [SSM] end =====

        # reg
        reg_embedding_loss_v = (self.v_preference[user] ** 2).mean() if self.v_preference is not None else 0.0
        reg_embedding_loss_t = (self.t_preference[user] ** 2).mean() if self.t_preference is not None else 0.0
        reg_loss = self.reg_weight * (reg_embedding_loss_v + reg_embedding_loss_t)
        reg_loss += self.reg_weight * (self.weight_u ** 2).mean()

        # mask
        with torch.no_grad():
            u_temp, i_temp = self.user_rep.clone(), self.item_rep.clone()
            u_temp2, i_temp2 = self.user_rep.clone(), self.item_rep.clone()
            u_temp.detach()
            i_temp.detach()
            u_temp2.detach()
            i_temp2.detach()
            u_temp2 = self.mlp(u_temp2)
            i_temp2 = self.mlp(i_temp2)
            u_temp = F.dropout(u_temp, self.dropout)
            i_temp = F.dropout(i_temp, self.dropout)
        mask_loss_u = 1 - F.cosine_similarity(u_temp, u_temp2).mean()
        mask_loss_i = 1 - F.cosine_similarity(i_temp, i_temp2).mean()
        mask_f_loss = self.mask_weight_f * (mask_loss_i + mask_loss_u)

        # guide
        # 粗粒度-分布
        r_var, r_mean, g_var, g_mean, v_var, v_mean, t_var, t_mean = self.fit_Gaussian_dis()
        # id and v+t
        # dis_loss_i_vt = (torch.abs(g_var - r_var) +
        #                  torch.abs(g_mean - r_mean)).mean()
        # # id and v
        # dis_loss_i_v = (torch.abs(g_var - v_var) +
        #                 torch.abs(g_mean - v_mean)).mean()
        # # id and t
        # dis_loss_i_t = (torch.abs(g_var - t_var) +
        #                 torch.abs(g_mean - t_mean)).mean()
        #
        # # v and v+t
        # dis_loss_v_vt = (torch.abs(r_var - v_var) +
        #                  torch.abs(r_mean - v_mean)).mean()
        #
        # # t and v+t
        # dis_loss_t_vt = (torch.abs(r_var - t_var) +
        #                  torch.abs(r_mean - t_mean)).mean()
        #
        # # v and t
        # dis_loss_v_t = (torch.abs(v_var - t_var) +
        #                 torch.abs(v_mean - t_mean)).mean()
        #
        # # total
        # dis_loss = (dis_loss_i_vt + dis_loss_i_v + dis_loss_i_t
        #             + dis_loss_v_vt + dis_loss_t_vt
        #             + dis_loss_v_t)

        # level4
        # dis_loss = (dis_loss_v_t)
        # level3
        # dis_loss = (dis_loss_v_vt + dis_loss_t_vt)
        # level2
        # dis_loss = (dis_loss_i_v + dis_loss_i_t)
        # level1
        # dis_loss = dis_loss_i_vt

        align_loss = ((torch.abs(g_var - r_var) +
                         torch.abs(g_mean - r_mean)).mean() +
                        (torch.abs(g_var - v_var) +
                         torch.abs(g_mean - v_mean)).mean() +
                       (torch.abs(g_var - t_var) +
                        torch.abs(g_mean - t_mean)).mean() +
                      (torch.abs(r_var - v_var) +
                       torch.abs(r_mean - v_mean)).mean() +
                     (torch.abs(r_var - t_var) +
                      torch.abs(r_mean - t_mean)).mean() +
                    (torch.abs(v_var - t_var) +
                     torch.abs(v_mean - t_mean)).mean())

        # 图噪音cl
        # inspired by SimGCL
        mask_g_loss = (self.InfoNCE(self.result_embed_n1[:self.n_users], self.result_embed_n2[:self.n_users], self.temp)
                       + self.InfoNCE(self.result_embed_n1[self.n_users:], self.result_embed_n2[self.n_users:], self.temp))

        mask_g_loss = mask_g_loss * self.mask_weight_g

        align_loss = align_loss * self.align_weight

        return loss_value + reg_loss + align_loss + mask_f_loss + mask_g_loss

        # return loss_value + reg_loss

    def full_sort_predict(self, interaction):
        user_ids = interaction[0]
        user_tensor = self.result_embed[:self.n_users]
        item_tensor = self.result_embed[self.n_users:]
        score_matrix = torch.matmul(user_tensor[user_ids], item_tensor.t())

        guide_user_tensor = self.result_embed_guide[:self.n_users]
        guide_item_tensor = self.result_embed_guide[self.n_users:]
        guide_score_matrix = torch.matmul(guide_user_tensor[user_ids], guide_item_tensor.t())
        return score_matrix + self.id_residual_scale() * guide_score_matrix

    def topk_sample(self, k):
        user_graph_index = []
        count_num = 0
        user_weight_matrix = torch.zeros(len(self.user_graph_dict), k)
        tasike = []
        for i in range(k):
            tasike.append(0)
        for i in range(len(self.user_graph_dict)):
            if len(self.user_graph_dict[i][0]) < k:
                count_num += 1
                if len(self.user_graph_dict[i][0]) == 0:
                    # pdb.set_trace()
                    user_graph_index.append(tasike)
                    continue
                user_graph_sample = self.user_graph_dict[i][0][:k]
                user_graph_weight = self.user_graph_dict[i][1][:k]
                while len(user_graph_sample) < k:
                    rand_index = np.random.randint(0, len(user_graph_sample))
                    user_graph_sample.append(user_graph_sample[rand_index])
                    user_graph_weight.append(user_graph_weight[rand_index])
                user_graph_index.append(user_graph_sample)

                user_weight_matrix[i] = F.softmax(torch.tensor(user_graph_weight), dim=0)  # softmax
                continue
            user_graph_sample = self.user_graph_dict[i][0][:k]
            user_graph_weight = self.user_graph_dict[i][1][:k]

            user_weight_matrix[i] = F.softmax(torch.tensor(user_graph_weight), dim=0)  # softmax
            user_graph_index.append(user_graph_sample)

        # pdb.set_trace()
        return user_graph_index, user_weight_matrix

    def print_embd(self):
        return self.result_embed_v, self.result_embed_t


class GCN(torch.nn.Module):
    def __init__(self, datasets, batch_size, num_user, num_item, dim_id, aggr_mode,
                 dim_latent=None, device=None, features=None):
        super(GCN, self).__init__()
        self.batch_size = batch_size
        self.num_user = num_user
        self.num_item = num_item
        self.datasets = datasets
        self.dim_id = dim_id
        self.dim_feat = features.size(1)
        self.dim_latent = dim_latent
        self.aggr_mode = aggr_mode
        self.device = device

        if self.dim_latent:
            self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                np.random.randn(num_user, self.dim_latent), dtype=torch.float32, requires_grad=True),
                gain=1).to(self.device))
            self.MLP = nn.Linear(self.dim_feat, 4 * self.dim_latent)
            self.MLP_1 = nn.Linear(4 * self.dim_latent, self.dim_latent)
            self.conv_embed_1 = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)

        else:
            self.preference = nn.Parameter(nn.init.xavier_normal_(torch.tensor(
                np.random.randn(num_user, self.dim_feat), dtype=torch.float32, requires_grad=True),
                gain=1).to(self.device))
            self.conv_embed_1 = Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)

    def forward(self, edge_index_drop, edge_index, features, perturbed=False):
        temp_features = self.MLP_1(F.leaky_relu(self.MLP(features))) if self.dim_latent else features
        x = torch.cat((self.preference, temp_features), dim=0).to(self.device)
        x = F.normalize(x).to(self.device)

        h = self.conv_embed_1(x, edge_index)
        if perturbed:
            random_noise = torch.rand_like(h).to(h.device)
            h += torch.sign(h) * F.normalize(random_noise, dim=-1) * 0.1
        h_1 = self.conv_embed_1(h, edge_index)
        if perturbed:
            random_noise = torch.rand_like(h_1).to(h_1.device)
            h_1 += torch.sign(h_1) * F.normalize(random_noise, dim=-1) * 0.1
        # h_2 = self.conv_embed_1(h_1, edge_index)

        x_hat = x + h + h_1
        return x_hat, self.preference


class Base_gcn(MessagePassing):
    def __init__(self, in_channels, out_channels, normalize=True, bias=True, aggr='add', **kwargs):
        super(Base_gcn, self).__init__(aggr=aggr, **kwargs)
        self.aggr = aggr
        self.in_channels = in_channels
        self.out_channels = out_channels

    def forward(self, x, edge_index, size=None):
        # pdb.set_trace()
        if size is None:
            edge_index, _ = remove_self_loops(edge_index)
            # edge_index, _ = add_self_loops(edge_index, num_nodes=x.size(0))
        x = x.unsqueeze(-1) if x.dim() == 1 else x
        # pdb.set_trace()
        return self.propagate(edge_index, size=(x.size(0), x.size(0)), x=x)

    def message(self, x_j, edge_index, size):
        if self.aggr == 'add':
            # pdb.set_trace()
            row, col = edge_index
            deg = degree(row, size[0], dtype=x_j.dtype)
            deg_inv_sqrt = deg.pow(-0.5)
            norm = deg_inv_sqrt[row] * deg_inv_sqrt[col]
            return norm.view(-1, 1) * x_j
        return x_j

    def update(self, aggr_out):
        return aggr_out

    def __repr(self):
        return '{}({},{})'.format(self.__class__.__name__, self.in_channels, self.out_channels)
